### ISSUE TITLE
[Request]云函数部署下报错

### ISSUE THREAD

**Issue by ZiuChen** [chinjiaqing/juejin-helper#1]
GithubAction有封号风险，我希望能部署云函数环境执行

我简单修改尝试了一下，部署到了腾讯云函数中执行代码，但是出现报错:

```json
{
    "errorCode": -1,
    "errorMessage": "DatabaseError: Can't save the database     at JsonDB.save (/var/user/node_modules/node-json-db/dist/JsonDB.js:369:27)     at JsonDB.push (/var/user/node_modules/node-json-db/dist/JsonDB.js:279:18)     at Object.<anonymous> (/var/user/utils/db.js:8:4)     at Module._compile (node:internal/modules/cjs/loader:1101:14)     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)     at Module.load (node:internal/modules/cjs/loader:981:32)     at Function.Module._load (node:internal/modules/cjs/loader:822:12)     at Module.require (node:internal/modules/cjs/loader:1005:19)     at require (node:internal/modules/cjs/helpers:102:18)     at Object.<anonymous> (/var/user/juejin/task/collect-article.js:4:22)",
    "statusCode": 443
}
```

![image](https://user-images.githubusercontent.com/64892985/180001805-c379cc7e-2029-4df1-a911-6ba6570f584d.png)

查阅了[NPM - node-json-db](https://www.npmjs.com/package/node-json-db)里面有这么一条:

> Can't save the database: XXX
> DatabaseError
> JsonDB can't save the database for "err" reason. You can find the nested error in error.inner

云函数环境下，无法对已部署的代码进行修改，自然就无法持久化保存脚本的操作记录

针对操作记录的存储部分，能否：

* 提供环境变量参数，支持配置是否存储操作记录
* 采用其他方式存储操作记录

**Comment by chinjiaqing** [comment]
> GithubAction有封号风险，我希望能部署云函数环境执行
> 
> 我简单修改尝试了一下，部署到了腾讯云函数中执行代码，但是出现报错:
> 
> ```json
> {
>     "errorCode": -1,
>     "errorMessage": "DatabaseError: Can't save the database     at JsonDB.save (/var/user/node_modules/node-json-db/dist/JsonDB.js:369:27)     at JsonDB.push (/var/user/node_modules/node-json-db/dist/JsonDB.js:279:18)     at Object.<anonymous> (/var/user/utils/db.js:8:4)     at Module._compile (node:internal/modules/cjs/loader:1101:14)     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)     at Module.load (node:internal/modules/cjs/loader:981:32)     at Function.Module._load (node:internal/modules/cjs/loader:822:12)     at Module.require (node:internal/modules/cjs/loader:1005:19)     at require (node:internal/modules/cjs/helpers:102:18)     at Object.<anonymous> (/var/user/juejin/task/collect-article.js:4:22)",
>     "statusCode": 443
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/64892985/180001805-c379cc7e-2029-4df1-a911-6ba6570f584d.png)
> 
> 查阅了[NPM - node-json-db](https://www.npmjs.com/package/node-json-db)里面有这么一条:
> 
> > Can't save the database: XXX
> > DatabaseError
> > JsonDB can't save the database for "err" reason. You can find the nested error in error.inner
> 
> 云函数环境下，无法对已部署的代码进行修改，自然就无法持久化保存脚本的操作记录
> 
> 针对操作记录的存储部分，能否：
> 
> * 提供环境变量参数，支持配置是否存储操作记录
> * 采用其他方式存储操作记录
