### ISSUE TITLE
我Fork下之后，定时运行总是被跳过，如何处理呢？

### ISSUE THREAD

**Issue by MatthewTt** [chinjiaqing/juejin-helper#4]
![image](https://user-images.githubusercontent.com/23712720/194976506-b17051af-7ed1-415e-8896-015140a4cb54.png)
![image](https://user-images.githubusercontent.com/23712720/194976521-987c2f1b-8c26-4749-ba3f-b29cc127fdf0.png)

**Comment by chinjiaqing** [comment]
拉一下最新代码
